### ISSUE TITLE
`rst ls` tries to load Vim swap files, and chokes

### ISSUE THREAD

**Issue by IslandUsurper** [vitiral/rst#4]
During `rst tutorial 4`, I had flash/load.py open when I ran `rst ls SPC-load-format` which would show that the SPC was completed. However, I got the following error instead until I closed the file:

> ERROR: while reading from </{redacted}/flash/.load.py.swp>: stream did not contain valid UTF-8
> ERROR: Parse Errors: encountered errors while finding locations

I'm fairly certain that Vim's swap file format is binary, and just happens to have a bunch of text-like data in it, so the error is _true_ for what that's worth. I'm also not sure what should be done about it. Since I'm a Vim user, this is annoying, but I also understand this would be a generic tool and some people might want the ability to search any and every file in "code_paths".

I'm leaning toward suggesting a configuration option that defaults to ignoring files that start with ".". I believe that's a common enough system that it makes a reasonable default.

**Comment by vitiral** [comment]
it shouldn't be throwing errors for non-text files. I was going to add a config option so that you could only load certain extentions for src files. I'll have to do that sooner rather than later.

I could also convert that particular error to a warning instead of an ERROR. I think I will do that first.

In the meatime, you can work around the issue like this:

http://stackoverflow.com/questions/1636297/how-to-change-the-folder-path-for-swp-files-in-vim

```
# add to ~/.vimrc
:set dir=~/MY_TEMP_FOLDER
```

I've used vim for a while, and I prefered the swap files being stored in a special directory instead of next to my code.
